// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_incidencias from "./routes/api/incidencias.ts";
import * as $index from "./routes/index.tsx";
import * as $IncidenciasList from "./islands/IncidenciasList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/incidencias.ts": $api_incidencias,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/IncidenciasList.tsx": $IncidenciasList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
