// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_audit from "./routes/api/audit.ts";
import * as $api_incidencias from "./routes/api/incidencias.ts";
import * as $api_tareas from "./routes/api/tareas.ts";
import * as $incidencia_id_ from "./routes/incidencia/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $AuditLog from "./islands/AuditLog.tsx";
import * as $IncidenciasList from "./islands/IncidenciasList.tsx";
import * as $TareasIncidencia from "./islands/TareasIncidencia.tsx";
import * as $TareasIncidenciaList from "./islands/TareasIncidenciaList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/audit.ts": $api_audit,
    "./routes/api/incidencias.ts": $api_incidencias,
    "./routes/api/tareas.ts": $api_tareas,
    "./routes/incidencia/[id].tsx": $incidencia_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AuditLog.tsx": $AuditLog,
    "./islands/IncidenciasList.tsx": $IncidenciasList,
    "./islands/TareasIncidencia.tsx": $TareasIncidencia,
    "./islands/TareasIncidenciaList.tsx": $TareasIncidenciaList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
